"""Where uploaded pictures are kept.

Two backends behind one interface:

* ``LocalStorage`` writes into ``app/static/uploads``. Fine on a normal server
  and on a laptop; useless on a serverless host, where the filesystem is
  read-only apart from /tmp and is discarded when the function is recycled.
* ``SupabaseStorage`` puts the bytes in a Supabase Storage bucket and serves
  them from Supabase's CDN, so they outlive any one deployment.

Both address a file by the same key — ``uploads/<filename>`` — so a database row
written by one backend still resolves under the other, and switching hosts does
not rewrite the ``media_assets`` table.
"""
import json
import mimetypes
import os
import urllib.error
import urllib.request

from flask import current_app, url_for

# Keys we hand out and understand. Anything else is a file that ships with the
# app (the car illustrations, the favicon) and is served by Flask as usual.
UPLOAD_PREFIX = "uploads/"


class StorageError(RuntimeError):
    """Something went wrong talking to the storage backend."""


class LocalStorage:
    name = "local"

    def __init__(self, root):
        self.root = root
        os.makedirs(self.root, exist_ok=True)

    def _path(self, key):
        # Keys are generated by this application, never by a request, but a
        # traversal here would write outside the upload directory, so check.
        filename = key[len(UPLOAD_PREFIX):] if key.startswith(UPLOAD_PREFIX) else key
        if "/" in filename or "\\" in filename or filename in ("", ".", ".."):
            raise StorageError(f"Refusing to touch {key!r}.")
        return os.path.join(self.root, filename)

    def save(self, key, data, content_type=None):
        with open(self._path(key), "wb") as handle:
            handle.write(data)

    def delete(self, key):
        path = self._path(key)
        if os.path.exists(path):
            os.remove(path)

    def url(self, key):
        return url_for("static", filename=key)


class SupabaseStorage:
    """Supabase Storage over its REST API.

    Deliberately uses urllib rather than a client library: this is three HTTP
    calls, and every dependency added here is weight in a serverless bundle.
    """

    name = "supabase"

    def __init__(self, base_url, service_key, bucket, cache_seconds=31536000):
        if not base_url or not service_key:
            raise StorageError(
                "Supabase storage needs SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY."
            )
        self.base_url = base_url.rstrip("/")
        self.service_key = service_key
        self.bucket = bucket
        self.cache_seconds = cache_seconds

    def _object_url(self, key):
        return f"{self.base_url}/storage/v1/object/{self.bucket}/{key}"

    def _request(self, method, url, data=None, content_type=None):
        headers = {
            "Authorization": f"Bearer {self.service_key}",
            "apikey": self.service_key,
        }
        if content_type:
            headers["Content-Type"] = content_type
            headers["Cache-Control"] = f"max-age={self.cache_seconds}"
        request = urllib.request.Request(url, data=data, headers=headers, method=method)
        try:
            with urllib.request.urlopen(request, timeout=20) as response:
                return response.status, response.read()
        except urllib.error.HTTPError as error:
            body = error.read().decode("utf-8", "replace")[:400]
            message = body
            try:
                message = json.loads(body).get("message", body)
            except ValueError:
                pass
            raise StorageError(f"Supabase storage said {error.code}: {message}") from error
        except urllib.error.URLError as error:
            raise StorageError(f"Could not reach Supabase storage: {error.reason}") from error

    def save(self, key, data, content_type=None):
        content_type = content_type or mimetypes.guess_type(key)[0] or "application/octet-stream"
        self._request("POST", self._object_url(key), data=data, content_type=content_type)

    def delete(self, key):
        try:
            self._request("DELETE", self._object_url(key))
        except StorageError as error:
            # A file already gone is the state we wanted; anything else is real.
            if "404" not in str(error) and "not found" not in str(error).lower():
                raise

    def url(self, key):
        return f"{self.base_url}/storage/v1/object/public/{self.bucket}/{key}"


def build_storage(app):
    """Pick a backend from configuration."""
    backend = app.config.get("STORAGE_BACKEND")
    if backend is None:
        # Not stated: use Supabase when it is configured, otherwise local disk.
        backend = "supabase" if app.config.get("SUPABASE_URL") else "local"

    if backend == "supabase":
        return SupabaseStorage(
            app.config["SUPABASE_URL"],
            app.config["SUPABASE_SERVICE_ROLE_KEY"],
            app.config["SUPABASE_STORAGE_BUCKET"],
            app.config["UPLOAD_CACHE_SECONDS"],
        )
    if backend == "local":
        return LocalStorage(app.config["UPLOAD_FOLDER"])
    raise StorageError(f"Unknown storage backend {backend!r}.")


def get_storage(app=None):
    app = app or current_app
    storage = app.extensions.get("jatta_storage")
    if storage is None:
        storage = build_storage(app)
        app.extensions["jatta_storage"] = storage
    return storage


def media_url(path):
    """URL for anything an image field might hold.

    Uploaded files go through the storage backend; everything else is a file
    that ships with the app and is served from /static as normal.
    """
    if not path:
        return ""
    if path.startswith(UPLOAD_PREFIX):
        return get_storage().url(path)
    return url_for("static", filename=path)
